# Generated by Django 4.2.7 on 2023-11-09 17:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
